### PR TITLE
Added basejail functionality.

### PR DESCRIPTION
**Pull request by skarekrow**
Not fully working yet. The extract process currently is not 100% working. Looking to fix it up here. Have not tested the startup routine as the creation one hasn't fully finished yet. Also haven't tested upgrading with this method.

### CODE REVIEW

**Comment by pannon** [comment]
Will need to be careful with this one. Both basejail and independent jails should be transparently supported. Perhaps have separate RELEASE ZFS datasets for basejails.

**Comment by skarekrow** [comment]
Right via as discussed it wait for the fast file copying for ZFS which
would let us "copy" the data but do it instantly and without additional
space consumption. Look at the GNU cp --reflink as that is the same
principle. Would be a boon for us I think instead of having to revisit this
another time.

**Comment by skarekrow** [comment]
via *cpio sorry the phone mangled that. I see you committed base jail functionality but currently the jails don't start with it with the method you committed?

**Comment by skarekrow** [comment]
You also said you wanted usr/src and usr/ports included and those are not as well. Is there a reason?

**Comment by pannon** [comment]
It is still WIP, will be committing pieces in the coming days. Ports and src will need to be optional and ports need a bit more work too.

**Comment by skarekrow** [comment]
Alright I'm still working on the starting of the jails. Do you need me to do that? Should I close this PR?

**Comment by skarekrow** [comment]
Lots has changed so far and I think it' s going to be completely redone after looking at how you did basejail creation. I think I will mimic that for the starting of them.

**Comment by pannon** [comment]
Yes and there will be a few changes going into it, it is a larger piece of work as it will need to touch multiple functions.

**Comment by skarekrow** [comment]
Rewrote it, still breaking though. Not sure what else to do. Maybe you have suggestions.

**Comment by skarekrow** [comment]
Also this currently requires the user to ```iocage set use_basejail="yes" UUID|TAG``` before it does anything.

**Comment by skarekrow** [comment]
Yours is better!

**Pull request closed without merging**
