### PR TITLE
Changed instances of /iocage to $iocroot

### PR DESCRIPTION
**Pull request by pr1ntf**
I wanted to make it easier to store iocage jails along with all my other virtualization solutions on the same ZFS pool. Having iocage live in /iocage didn't fit with what I had built, so I brought the mountain to my backup and snapshot scripts. 
This way, my zpool looks like:
zpool
zpool/vbox
zpool/bhyve
zpool/ezjail
zpool/iocage

### CODE REVIEW

**Comment by skarekrow** [comment]
Thanks for redoing this!

**Comment by pr1ntf** [comment]
I gotta learn how to get sometime, right?

**Comment by skarekrow** [comment]
:)

**Comment by pannon** [comment]
Was this tested with latest?

**Comment by pr1ntf** [comment]
I tried fetch with the latest and it seemed to work. I have not fully tested with latest. Still throws the 'unexpected /' error when asking for pool.

**Comment by pannon** [comment]
Throws "unexpected /" with $iocroot but works fine without?

**Comment by skarekrow** [comment]
If you tried changing the iocroot variable to iocage instead of /iocage and then having /$iocroot instead of $iocroot everywhere else? Maybe that fixes it.

**Comment by pr1ntf** [comment]
That error was around before iocroot. Fetch wants a pool, not file tree I'm guessing? It will still fetch to /neuralnet/iocage though.

**Comment by pr1ntf** [comment]
As in issue 28

**Comment by pannon** [comment]
So it only happens the first time you run iocage - i.e. when the pool is set up?

**Comment by pr1ntf** [comment]
Correct.

**Comment by pannon** [comment]
Are you supplying poolname/filesystem when it prompts for a pool?

**Comment by pr1ntf** [comment]
Yes. Just as the opening of issue #28. 
"cannot open 'neuralnet/iocage': invalid character '/' in pool name"

**Comment by pannon** [comment]
OK, you are not supposed to supply filesystem at that prompt. It is only expecting a pool name.

**Comment by pr1ntf** [comment]
Yeah I figured it was expected behavior. That's the only issue I ran into so far.

**Pull request merged**
