### PR TITLE
Fixed small typo and added upgrade to basejails.

### PR DESCRIPTION
**Pull request by skarekrow**

### CODE REVIEW

**Comment by skarekrow** [comment]
Don't merge yet. We need to discuss this. Currently it is overwriting the files. It needs to merge the differences. Not sure how to approach that.

**Comment by skarekrow** [comment]
@pannon Any ideas?

**Comment by pannon** [comment]
@skarekrow reclone function already does most of this pull request. The `bdir` directories should not be re-copied either. We can have a look for merging `/etc` somehow - or suggest the user to do it manually.

**Comment by skarekrow** [comment]
The reclone does not currently upgrade releases properly. 10.0-RELEASE to
10.1-RELEASE does not function. Same reason I have bdir in this PR. How
would the user do it manually? The files are never created to look at for a
merge. They are still from the same old RELEASE.

**Comment by pannon** [comment]
But if you re-copy all bdirs then you overwrite valid configuration in `/etc` and possibly other bits. Will need to investigate `mergemaster` to do merging.

**Comment by skarekrow** [comment]
Correct that's the part I was talking about. Recloning does not work as it was. So I had to essentially recreate it for the upgrade path. But I agree, bdir needs to be removed and we need to mergemaster from the basejail to the upgraded jails. I wasn't sure if it would work though. Need to look into it. I've only used the tool a handful of times.

**Comment by pannon** [comment]
Have tested this and there is a glitch when RELEASE is set to NEWRELEASE - you were right it fails to reclone. I will fix this inside __reclone...

**Comment by skarekrow** [comment]
Sounds good. So I'll close this PR and if I have some time I'll open a new
one with mergemaster.

**Comment by pannon** [comment]
OK just pushed a fox for this. Existing basejails will need to be destroyed, new ones should work fine.

**Comment by skarekrow** [comment]
Sounds good.

**Pull request closed without merging**
